---
- name: installing packages for python env
  become: yes
  apt:
    name:
      - python3-pip
    update_cache: yes

- name: Create directory
  file:
    path: ./basic-http-server
    state: directory

- name: Creating an empty file
  file:
    path: ./basic-http-server/test.txt
    state: touch

- name: Creating file with content
  copy:
    dest: ./basic-http-server/my-content.txt
    content: |
      Hello world.
      Hello my dear, you'r my world.

# - name: install apache2
#   become: yes
#   apt: name=apache2 update_cache:yes state:latest